spring:
  application:
    name: eureka-server

eureka:
  server:
    #不开启自我保护状态（心跳失败的比例，在15分钟内是否低于85%,
    #如果出现了低于的情况，Eureka Server会将当前的实例注册信息保护起来，
    #同时提示一个警告，一旦进入保护模式，Eureka Server将会尝试保护其服务
    #注册表中的信息，不再删除服务注册表中的数据。也就是不会注销任何微服务）
    enable-self-preservation: false
---
spring:
  profiles: eureka1
server:
  port: 2001

eureka:
  instance:
    #区分不同的eureka服务器
    hostname: eureka1
  client:
    #不向自身注册(拉取会用自身覆盖公共部分)
    register-with-eureka: false
    #不从自身拉取注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://eureka2:2002/eureka

---
spring:
  profiles: eureka2
server:
  port: 2002

eureka:
  instance:
    #区分不同的eureka服务器
    hostname: eureka2
  client:
    #不向自身注册
    register-with-eureka: false
    #不从自身拉取注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://eureka1:2001/eureka

